"""remove is_ favorite flag to user vocabulary

Revision ID: b4235a645c58
Revises: be03cefec9d9
Create Date: 2026-09-27 01:56:52.994369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4235a645c58'
down_revision: Union[str, Sequence[str], None] = 'be03cefec9d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_vocabularies', 'is_favorite')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_vocabularies', sa.Column('is_favorite', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
