"""add favorite flag to user vocabulary

Revision ID: be03cefec9d9
Revises: b524c72a47a4
Create Date: 2026-09-27 01:52:36.990372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be03cefec9d9'
down_revision: Union[str, Sequence[str], None] = 'b524c72a47a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_vocabularies', sa.Column('is_favorite', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_vocabularies', 'is_favorite')
    # ### end Alembic commands ###
